# zsh config file
# uploaded on Github: ValentinMENDIss

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"
eval "$(starship init zsh)"

# Set up spaceship prompt for zsh
# source "$HOME/.zsh/spaceship/spaceship.zsh"

alias -g cat="bat"

# Print 
cowsay -f eyes "Welcome to the world of Linux, let's see where it will get us"
