# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist USE flag enabled

ACCEPT_LICENSE="*"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://nereid.fr.ext.planetunix.net/pub/gentoo/ \
    ftp://nereid.fr.ext.planetunix.net/pub/gentoo/ \
    rsync://nereid.fr.ext.planetunix.net/gentoo/ \
    https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ \
    rsync://mirror.eu.oneandone.net/gentoo/ \
    https://ftp.agdsn.de/gentoo \
    rsync://ftp.agdsn.de/gentoo \
    https://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/ \
    rsync://ftp.spline.inf.fu-berlin.de/gentoo-distfiles/ \
    https://mirror.leaseweb.com/gentoo/ \
    rsync://mirror.leaseweb.com/gentoo/"

VIDEO_CARDS="intel nvidia"
INPUT_DEVICES="libinput"

USE="wayland X Xwayland aac alsa pipewire acl encode ffmpeg extra mp3 mp4 mpeg networkmanager grub bluetooth dracut dist-kernel -systemd -gnome -kde -dvd -dvdr -emacs -xemacs -ipad -ios" 
GRUB_PLATFORMS="efi-64"
