# zsh config file
# uploaded on Github: ValentinMENDIss

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

# Set up spaceship prompt for zsh
source "$HOME/.zsh/spaceship/spaceship.zsh"
