#! /bin/sh
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	Author	-	ValentinMENDIss
#	Repo	-	https://github.com/ValentinMENDIss/Dotfiles


#   ___       __            ______                                          
#   __ |     / /_______________  /______________________ ___________________
#   __ | /| / /_  __ \_  ___/_  //_/_  ___/__  __ \  __ `/  ___/  _ \_  ___/
#   __ |/ |/ / / /_/ /  /   _  ,<  _(__  )__  /_/ / /_/ // /__ /  __/(__  ) 
#   ____/|__/  \____//_/    /_/|_| /____/ _  .___/\__,_/ \___/ \___//____/  
#                                      /_/                               

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


#   __________________________       _______  ___   ____________________   __________________________
#   ___  __ )_  ___/__  __ \_ |     / /__   |/  /   __  ____/_  __ \__  | / /__  ____/___  _/_  ____/
#   __  __  |____ \__  /_/ /_ | /| / /__  /|_/ /    _  /    _  / / /_   |/ /__  /_    __  / _  / __  
#   _  /_/ /____/ /_  ____/__ |/ |/ / _  /  / /     / /___  / /_/ /_  /|  / _  __/   __/ /  / /_/ /  
#   /_____/ /____/ /_/     ____/|__/  /_/  /_/      \____/  \____/ /_/ |_/  /_/      /___/  \____/   
                                                                                                 



bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_size
bspc config pointer_action3         resize_corner

bspc rule -a scratch sticky=on state=floating focus=on


#   _______       _____      ____________              _____ 
#   ___    |___  ___  /________  ___/_  /______ _________  /_
#   __  /| |  / / /  __/  __ \____ \_  __/  __ `/_  ___/  __/
#   _  ___ / /_/ // /_ / /_/ /___/ // /_ / /_/ /_  /   / /_  
#   /_/  |_\__,_/ \__/ \____//____/ \__/ \__,_/ /_/    \__/  
                                                        
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &

